version: 2
updates:
  # Frontend dependencies (React.js, Next.js, Tailwind CSS)
  - package-ecosystem: "npm"
    directory: "/frontend" # adjust if at root
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(frontend)"
    labels:
      - "dependencies"
      - "frontend"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Backend dependencies (Node.js, Express)
  - package-ecosystem: "npm"
    directory: "/backend" # adjust if at root
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(backend)"
    labels:
      - "dependencies"
      - "backend"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
    labels:
      - "dependencies"
      - "ci"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Docker dependencies (Supabase, Node images, Postgres)
  - package-ecosystem: "docker"
    directory: "/" 
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(docker)"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

# Optional: Automerge config for safe patch updates only
automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "version-update:semver-patch"

