// 
//  * Copyright (c) 2025 Cosmo Exploit Group LLC. All Rights Reserved.
//  * 
//  * PROPRIETARY AND CONFIDENTIAL
//  * 
//  * This file is part of the Cosmo Exploit Group LLC Weight Management System.
//  * Unauthorized copying of this file, via any medium is strictly prohibited.
//  * 
//  * This file contains proprietary and confidential information of 
//  * Cosmo Exploit Group LLC and may not be copied, distributed, or used
//  * in any way without explicit written permission.
//  
// 

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
        - NEXT_PUBLIC_CESIUM_TOKEN=${NEXT_PUBLIC_CESIUM_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXT_PUBLIC_CESIUM_TOKEN=${NEXT_PUBLIC_CESIUM_TOKEN}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder # Use the builder stage for development
      args:
        - NODE_ENV=development
        - SUPABASE_URL=${SUPABASE_URL}
        - SUPABASE_KEY=${SUPABASE_KEY}
        - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    command: npm run dev

volumes:
  frontend-node-modules:
  backend-node-modules:
  
  
  Current State Analysis
Existing Pages:
/city/dashboard - Main dashboard overview
/city/weighing - Page for recording weights
Missing Pages (based on sidebar navigation):
/city/scales - Manage city scales
/city/permits - Manage permits
/city/violations - Track violations
/city/revenue - Revenue tracking
/city/reports - Generate reports
/city/map - Map view of scales/violations
/city/users - User management (admin only)
/city/profile - City profile settings (admin only)
/city/settings - System settings (admin only)
Existing API Routes:
/api/city-dashboard/stats
/api/city-dashboard/recent-weighings
/api/city-dashboard/revenue-data
/api/city-dashboard/compliance-data
/api/city-scales
