[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "cd frontend",
  "npm ci"
]

[phases.build]
cmds = [
  "cd frontend",
  "SKIP_ENV_VALIDATION=true npm run build"
]

[start]
cmd = "cd frontend && npm start"

[variables]
NODE_ENV = "production"
