// 
//  * Copyright (c) 2025 Cosmo Exploit Group LLC. All Rights Reserved.
//  * 
//  * PROPRIETARY AND CONFIDENTIAL
//  * 
//  * This file is part of the Cosmo Exploit Group LLC Weight Management System.
//  * Unauthorized copying of this file, via any medium is strictly prohibited.
//  * 
//  * This file contains proprietary and confidential information of 
//  * Cosmo Exploit Group LLC and may not be copied, distributed, or used
//  * in any way without explicit written permission.
//  
// 

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          container_name:
      - output:
          source: output

  - job_name: frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{container_name=~".*frontend.*"}'
          stages:
            - json:
                expressions:
                  log: log
            - labels:
                app: frontend
            - output:
                source: log

  - job_name: backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - docker: {}
      - match:
          selector: '{container_name=~".*backend.*"}'
          stages:
            - json:
                expressions:
                  log: log
            - labels:
                app: backend
            - output:
                source: log
